docs_dir: "docs"
site_dir: "static"
site_name: Pimidi Documentation
site_author: UAB VILNIAUS BLOKAS
use_directory_urls: true
theme:
  name: "material"
  favicon: "favicon.ico"
  logo: "images/logo.svg"
  palette:
    primary: "white"
    accent: "white"
  custom_dir: "blokas-docs-theme"
  features:
    - navigation.expand
    - navigation.instant
    - navigation.footer
site_url: https://blokas.io/pimidi/docs/
extra:
  ads:
    pisound: false
    patchboxos: false
    midihub: false
    modep: false
  discourse: "https://community.blokas.io/"
  disqus: "fake"
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/BlokasLabs"
    - icon: "fontawesome/brands/x-twitter"
      link: "https://twitter.com/blokaslabs"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/blokaslabs/"
  homepage: "https://blokas.io/pimidi/"
repo_name: "pimidi-docs"
repo_url: "https://github.com/BlokasLabs/pimidi-docs/"
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - footnotes:
      PLACE_MARKER: "///Footnotes Go Here///"

copyright: "&copy; 2024 VILNIAUS BLOKAS UAB"

nav:
  - Getting Started: index.md
  - Advanced Configuration: advanced-configuration.md
  - Detailed Specs: specs.md
  - Tutorials:
    - ALSA: alsa.md
    - Amidiminder: amidiminder.md
    - Pure Data: puredata.md
    - Python pimidipy:
      - pimidipy Patchbox Module: pimidipy-patchbox-module.md
      - pimidipy Library: pimidipy-library.md
      - pimidipy Reference: pimidipy-reference.md

plugins:
  - search
  - mkdocstrings:
      custom_templates: blokas-docs-theme/templates/mkdocstrings
      handlers:
        python:
          options:
            show_source: false
            docstring_style: sphinx
            show_root_heading: false
            show_root_toc_entry: false
            heading_level: 4
            show_bases: false
